#!/usr/bin/env ruby

require "scma_smartwaiver"

require 'smartwaiver-sdk/search_client'
require 'yaml'

SMARTWAIVER_API_KEY = ENV["SMARTWAIVER_API_KEY"]

client = SmartwaiverSearchClient.new(SMARTWAIVER_API_KEY)
results = client.search("", "2020-01-01 00:00:00")

# TODO check for errors
# $stderr.puts results.to_yaml

search = results[:search]

names = []
waivers = []
pages = search[:pages]
guid = search[:guid]

# DEBUG
# pages = 1

(0...pages.to_i).each do |page|
  results = client.results(guid, page)

  # TODO check for errors
  # $stderr.puts results.to_yaml

  waivers.push(*results[:search_results])
end

puts waivers.to_yaml
