#!/usr/bin/env ruby

require "scma_waivers"
require 'yaml'
require 'csv'
require "date"

def to_csv(waivers)
  CSV.generate do |csv|
    csv << ["Name", "Date", "Phone", "Emergency Contact", "Guardian"]
    waivers.each do |waiver|
      date = DateTime.parse(waiver[:createdOn]).strftime("%D")
      csv << [
        [waiver[:firstName], waiver[:lastName]].join(' '),
        date,
        waiver[:phone],
        waiver[:emergencyContact],
        waiver[:guardian],
      ]
    end
  end
end

waivers = YAML.load(ARGF.read)
puts to_csv(waivers)
