#!/usr/bin/env ruby

require "scma_waivers"

require "googleauth"
require "google/apis/sheets_v4"
require "google/apis/drive_v3"

require 'yaml'

Drive = Google::Apis::DriveV3
Sheets = Google::Apis::SheetsV4

SCOPES = [
  Drive::AUTH_DRIVE,
  Sheets::AUTH_SPREADSHEETS,
]

class App
  def initialize
    authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
      scope: SCOPES
    )

    @drive = Drive::DriveService.new
    @drive.authorization = authorizer

    @sheets = Sheets::SheetsService.new
    @sheets.authorization = authorizer
  end

  def create_spreadsheet(name:, shared_with:)
    spreadsheet = {
      properties: {
        title: name,
      }
    }
    spreadsheet = @sheets.create_spreadsheet(spreadsheet, fields: "spreadsheetId")
    $stderr.puts "spreadsheet_id:", spreadsheet.spreadsheet_id

    file_id = spreadsheet.spreadsheet_id
    permission = {
      type: "user",
      email_address: shared_with,
      role: "writer",
    }
    permission = @drive.create_permission(file_id, permission)
    $stderr.puts "permission:", permission

    spreadsheet.spreadsheet_id
  end

  def write_spreadsheet(id, waivers)
    rows = waivers.map do |waiver|
      [:firstName, :lastName, :createdOn, :phone, :emergencyContact, :guardian]
        .map { |k| waiver[k] }
    end

    row_objects = rows.map do |row|
      values = row.map do |cell|
        {
          user_entered_value: {
            string_value: cell,
          },
        }
      end
      { values: values }
    end

    request = {
      requests: [{
        update_cells: {
          rows: row_objects,
          fields: 'user_entered_value',
          start: {
            sheet_id: 0,
            row_index: 0,
            column_index: 0,
          },
        },
      }],
      include_spreadsheet_in_response: false,
    }

    require 'json'
    puts JSON.pretty_generate(request)
    result = begin
      @sheets.batch_update_spreadsheet(id, request)
    rescue Exception => e
      puts e.inspect
      puts JSON.load(e.body.inspect)
    end

    require 'pp'
    pp result
  end

  def main
    # id = create_spreadsheet(name: "SCMA Waivers", shared_with: ENV["SCMA_PAPER_WAIVERS_SHARED_WITH"])
    waivers = YAML.load(ARGF.read)
    id = ENV["SCMA_GSHEETS_WAIVERS_SHEET_ID"]
    write_spreadsheet(id, waivers)
  end
end

App.new.main
